DROP DATABASE gestion_bar;
CREATE DATABASE IF NOT EXISTS gestion_bar;
USE gestion_bar;

CREATE TABLE IF NOT EXISTS tables
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  number INT NOT NULL,
  nb_slot INT NOT NULL,
  available BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS foods
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price INT NOT NULL
);

/****************
 * GAME DATA
 ****************/

CREATE TABLE IF NOT EXISTS brands
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS authors
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS editors
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS languages
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS mecanisms
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS games
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_brand BIGINT NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  price INT NOT NULL,
  description_fr TEXT,
  description_en TEXT,
  player_min INT,
  player_max INT,
  age_min INT,
  age_max INT,
  duration_min INT,
  duration_max INT,
  FOREIGN KEY(id_brand) REFERENCES brands(id)
);


CREATE TABLE IF NOT EXISTS games_mecanisms
(
  id_game BIGINT NOT NULL,
  id_mecanism BIGINT NOT NULL,
  FOREIGN KEY(id_game) REFERENCES games(id),
  FOREIGN KEY(id_mecanism) REFERENCES mecanisms(id)
);

CREATE TABLE IF NOT EXISTS games_editors
(
  id_game BIGINT NOT NULL,
  id_editor BIGINT NOT NULL,
  FOREIGN KEY(id_game) REFERENCES games(id),
  FOREIGN KEY(id_editor) REFERENCES editors(id)
);

CREATE TABLE IF NOT EXISTS games_languages
(
  id_game BIGINT NOT NULL,
  id_language BIGINT NOT NULL,
  FOREIGN KEY(id_game) REFERENCES games(id),
  FOREIGN KEY(id_language) REFERENCES languages(id)
);

CREATE TABLE IF NOT EXISTS games_categories
(
  id_game BIGINT NOT NULL,
  id_category BIGINT NOT NULL,
  FOREIGN KEY(id_game) REFERENCES games(id),
  FOREIGN KEY(id_category) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS games_authors
(
  id_game BIGINT NOT NULL,
  id_author BIGINT NOT NULL,
  FOREIGN KEY(id_game) REFERENCES games(id),
  FOREIGN KEY(id_author) REFERENCES authors(id)
);

CREATE TABLE IF NOT EXISTS game_contents
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_game BIGINT NOT NULL,
  content TEXT,
  FOREIGN KEY(id_game) REFERENCES games(id)
);

CREATE TABLE IF NOT EXISTS game_pictures
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_game BIGINT NOT NULL,
  small VARCHAR(255),
  thickbox VARCHAR(255),
  large VARCHAR(255),
  FOREIGN KEY (id_game) REFERENCES games(id)
);

CREATE TABLE IF NOT EXISTS boards
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_game BIGINT NOT NULL,
  available BOOLEAN NOT NULL DEFAULT true,
  FOREIGN KEY(id_game) REFERENCES games(id)
);


CREATE TABLE IF NOT EXISTS tables_games
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_table BIGINT NOT NULL,
  id_game BIGINT NOT NULL,
  FOREIGN KEY(id_table) REFERENCES tables(id),
  FOREIGN KEY(id_game) REFERENCES games(id)
);

CREATE TABLE IF NOT EXISTS invoices
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_table BIGINT NOT NULL,
  id_board BIGINT NOT NULL,
  duration TIME,
  FOREIGN KEY(id_table) REFERENCES tables(id),
  FOREIGN KEY(id_board) REFERENCES boards(id)
);

CREATE TABLE IF NOT EXISTS invoices_foods
(
  id_invoice BIGINT NOT NULL,
  id_food BIGINT NOT NULL,
  FOREIGN KEY(id_invoice) REFERENCES invoices(id),
  FOREIGN KEY(id_food) REFERENCES foods(id)
);
