### Get request with a header
GET http://localhost:3000/tables
Accept: application/json

### Get request with a query
GET http://localhost:3000/tables?lol=dsdasda
Accept: application/json

### Get request for invoice by id
GET http://localhost:3000/invoices/1
Accept: application/json

